<a href="https://colab.research.google.com/github/anhnhat25dev/TH_DEEPLEARNING/blob/main/tensorflow_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
import tensorflow as tf

# Tensor scalar (0 chiều)

# mặc định int32
rank_0_tensor = tf.constant(4)

print(rank_0_tensor)

# chỉ định kiểu dữ liệu
r1 = tf.constant(9, tf.int16)
print(r1)

r1_float = tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant(
    'Hello Vanlang University',
    tf.string
)

print(r1_string)

# Tensor 1 chiều (vector)

rank_1_tensor = tf.constant([2.0, 3.0, 4.0])

print(rank_1_tensor)

# Tensor 2 chiều (matrix)

rank_2_tensor = tf.constant(
    [
        [1, 2],
        [3, 4],
        [5, 6]
    ],
    dtype=tf.float16
)

print(rank_2_tensor)


# Tensor 3 chiều


rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

print(rank_3_tensor)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Vanlang University', shape=(), dtype=string)
tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)
tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


các thuộc tính

In [3]:
import tensorflow as tf

rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],

    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],

    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])

print(rank_3_tensor)

print('shape:', rank_3_tensor.shape)

print('type of tensor:', rank_3_tensor.dtype)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


 tensor tự động gán giá trị 0 ban đầu

In [4]:
import tensorflow as tf

# Tensor 1 chiều toàn số 0

t_zero = tf.zeros(10)

print(t_zero)

# Tensor 2 chiều toàn số 0

t_2_zero = tf.zeros([3, 3])

print(t_2_zero)

# Tensor 3 chiều toàn số 0

t_3_zero = tf.zeros([3, 3, 5])

print(t_3_zero)

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)
