<a href="https://colab.research.google.com/github/anhnhat25dev/TH_DEEPLEARNING/blob/main/TUAN01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tạo array 1 chiều



In [2]:
import numpy as np

# cách 1
# tạo list
my_list = [1, 9, 15, 39]
print("Python list:", my_list)

# chuyển list --> Numpy array
my_numpy_array = np.array(my_list)
print("Numpy array:", my_numpy_array)

# cách 2
a = np.array([1, 9, 15, 39])
print(a)

Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
[ 1  9 15 39]


tạo array 2,3 chiều

In [3]:
import numpy as np

c = np.array([
    (1, 2, 3),
    (4, 5, 6)
])

print(c)
print(c.shape)
print(c.dtype)

########

d = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10, 11, 12]]
])

print(d)
print(d.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


tạo array với giá trị ban đầu là 0 hoặc 1

In [4]:
import numpy as np

# Tạo array toàn số 0
e = np.zeros((2, 2))

# Tạo array toàn số 1
f = np.ones((3, 3))

print("Zero matrix:\n", e)
print("One matrix\n", f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Reshape thay đổi kích thước ma trận

In [5]:
import numpy as np

# Reshape array 2 chiều

e = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])

print(e)
print(e.shape)

# đổi shape thành (3,2)
f = e.reshape(3, 2)

print(f)

# Reshape array 3 chiều

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])

print(g)
print(g.shape)

# reshape thành (3,4)
h = g.reshape(3, 4)
print("reshape (3, 4)\n", h)

# reshape thành (3,2,2)
j = g.reshape(3, 2, 2)
print("reshape (3, 2, 2)\n", j)

# reshape thành (2,3,2)
k = g.reshape(2, 3, 2)
print("reshape (2, 3, 2)\n", k)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)
[[1. 2.]
 [3. 4.]
 [5. 6.]]
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
reshape (3, 4)
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
reshape (3, 2, 2)
 [[[ 1.  2.]
  [ 3.  4.]]

 [[ 5.  6.]
  [ 7.  8.]]

 [[ 9. 10.]
  [11. 12.]]]
reshape (2, 3, 2)
 [[[ 1.  2.]
  [ 3.  4.]
  [ 5.  6.]]

 [[ 7.  8.]
  [ 9. 10.]
  [11. 12.]]]


 chuyển array nhiều chiều về 1 chiều

In [6]:
import numpy as np

# Flatten array 2 chiều về 1 chiều

e = np.array([
    [1., 2., 3.],
    [4., 5., 6.]
])

f = e.flatten()

print(f)

# Flatten array 3 chiều về 1 chiều

g = np.array([
    [[1., 2., 3.], [4., 5., 6.]],
    [[7., 8., 9.], [10., 11., 12.]]
])

j = g.flatten()

print(j)

[1. 2. 3. 4. 5. 6.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]


In [7]:
import numpy as np

# 3.7.1 Sinh mảng số nguyên ngẫu nhiên

a = np.random.randint(100, size=(5,))
print("Random 1-D array\n", a)

b = np.random.randint(100, size=(3, 4))
print("Random 2-D array\n", b)

c = np.random.randint(100, size=(3, 4, 3))
print("Random 3-D array\n", c)


# 3.7.2 Sinh số thực trong khoảng [0,1]

a = np.random.rand(5)
print("Random 1-D array\n", a)

b = np.random.rand(3, 4)
print("Random 2-D array\n", b)

c = np.random.rand(3, 4, 3)
print("Random 3-D array\n", c)


# 3.7.3 Phân phối chuẩn (normal distribution)
# mean = 5
# độ lệch chuẩn = 0.5
# sinh 10 số

a = np.random.normal(5, 0.5, 10)
print(a)


# 3.7.4 Chọn ngẫu nhiên từ tập giá trị cho trước

# sinh 1 giá trị ngẫu nhiên
a = np.random.choice([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])
print(a)

# sinh ma trận 3x5 ngẫu nhiên
b = np.random.choice(
    [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
    size=(3, 5)
)

print(b)

Random 1-D array
 [76 53 37 17 34]
Random 2-D array
 [[75 74 65 93]
 [20 62 36 95]
 [37 23 12 63]]
Random 3-D array
 [[[32 49 78]
  [ 7 80 97]
  [18 36  9]
  [54 14 91]]

 [[98 69 22]
  [91 30 10]
  [97 55 61]
  [69 80 33]]

 [[ 1 66 95]
  [14 77  3]
  [44 38 15]
  [53  5 15]]]
Random 1-D array
 [0.24216233 0.0728769  0.66425537 0.20387644 0.05842355]
Random 2-D array
 [[0.4516019  0.97188464 0.20914302 0.42134075]
 [0.861055   0.84893151 0.94302694 0.00830258]
 [0.91052613 0.34625046 0.42982668 0.96045117]]
Random 3-D array
 [[[0.41694391 0.80787926 0.68396981]
  [0.96106972 0.25415659 0.3941798 ]
  [0.9693263  0.74258874 0.43951236]
  [0.54880334 0.47361871 0.12505086]]

 [[0.5930716  0.44927843 0.13391176]
  [0.90920881 0.45507085 0.60802046]
  [0.51448184 0.44469785 0.45502328]
  [0.30483069 0.60511213 0.75577947]]

 [[0.86156692 0.38268479 0.06706845]
  [0.49942092 0.30229602 0.07684026]
  [0.15719403 0.25079537 0.58877191]
  [0.47045986 0.91472208 0.23868747]]]
[3.81814722 5.8855

PANDAS

In [8]:
import numpy as np
import pandas as pd

# =========================
# Pandas Series
# =========================

# tạo pandas series từ list
a = pd.Series([1., 2., 3.])

print(a)
print("First value:", a[0])

# tạo series có index
b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])

print(b)
print("First value:", b['a'])

# tạo pandas series từ dictionary
calories = {
    "day1": 420,
    "day2": 380,
    "day3": 390
}

myvar = pd.Series(calories)

print(myvar)

# =========================
# NumPy --> Pandas
# =========================

h = np.array([[1, 2], [3, 4]])

df_h = pd.DataFrame(h)

print("DataFrame:\n", df_h)

# =========================
# Pandas --> NumPy
# =========================

numpy_h = np.array(df_h)

print("Numpy array:\n", numpy_h)

# =========================
# Tạo DataFrame có tên cột
# =========================

dic = {
    'Name': ['John', 'Smith'],
    'Age': [30, 40]
}

df_dic = pd.DataFrame(dic)

print(df_dic)

# =========================
# Tạo DataFrame ngẫu nhiên
# =========================

r = np.random.randn(20, 4)

df = pd.DataFrame(
    r,
    columns=['s01', 's02', 's03', 's04']
)

print(df.head())  # in 5 dòng đầu tiên

# =========================
# Chọn dữ liệu
# =========================

# chọn 1 cột
print("Chọn cột s01\n", df['s01'])

# chọn nhiều dòng
print("Chọn nhiều dòng\n", df[0:3])

# chọn nhiều cột
print("Chọn nhiều cột\n", df[['s01', 's03']])

# chọn nhiều dòng, nhiều cột
print("Chọn nhiều dòng, nhiều cột\n", df.iloc[:3, :2])

# =========================
# Xóa cột
# =========================

df2 = df.drop(columns=['s01', 's04'])

print(df2)

# =========================
# Nối nhiều DataFrame
# =========================

df1 = pd.DataFrame({
    'Name': ['John', 'Smith', 'Paul'],
    'Age': [25, 30, 50]
}, index=[0, 1, 2])

df2 = pd.DataFrame({
    'Name': ['Adam', 'Smith'],
    'Age': [26, 11]
}, index=[3, 4])

# nối dataframe
df_concat = pd.concat([df1, df2])

print("Concate two DataFrame\n", df_concat)

# xóa dòng trùng Name
print(
    "Drop duplicates in DataFrame\n",
    df_concat.drop_duplicates('Name')
)

# sắp xếp theo cột Age
print(
    "Sort values in DataFrame\n",
    df_concat.sort_values('Age')
)

# đổi tên cột
df_rename = df_concat.rename(
    columns={
        'Name': 'Surname',
        'Age': 'Age_pupil'
    }
)

print("Rename columns of DataFrame\n", df_rename)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64
DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]
    Name  Age
0   John   30
1  Smith   40
        s01       s02       s03       s04
0 -0.840195  0.311400 -0.326515  0.132769
1 -0.626862  0.626621  0.716502 -1.467434
2  1.176230  0.883496 -0.557985 -0.084262
3 -1.355856  1.268573 -0.636445 -0.644388
4  0.415130  0.587780  1.505858  0.040524
Chọn cột s01
 0    -0.840195
1    -0.626862
2     1.176230
3    -1.355856
4     0.415130
5    -0.337498
6     0.283058
7     0.719130
8     1.471677
9    -2.099435
10   -0.100762
11    0.305710
12    0.346274
13   -1.176297
14    0.677929
15   -1.379677
16    1.236345
17    1.243385
18    0.294504
19   -0.754419
Name: s01, dtype: float64
Chọn nhiều dòng
         s01       s02       s03       s04
0 -0.840195  0.311400 -0.326515  0.132769
1 -0.626862  0.626621  0.716502 -